apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  password: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
data:
  auth_token: {{ .Values.secrets.auth_token | b64enc }}
  api_secret: {{ .Values.secrets.api_secret | b64enc }}

