database:
    password: ENC[AES256_GCM,data:pa16JfqdflrczSUpgbc=,iv:IypbzSW3rPC3ZFu5nMB40y1jmOBX+14AGSVp6AkoInQ=,tag:pv4Eh3NJaffbWoyrE4yN+A==,type:str]
secrets:
    auth_token: ENC[AES256_GCM,data:2S9+derGbOAC,iv:QszFWiBKKx5OHqFShYXXnkYMW8rmr/Gnwmr4qkXaXn4=,tag:NJXiLDQ85pSAW6TiwsTIUA==,type:str]
    api_secret: ENC[AES256_GCM,data:YtR7XWgkqXOM,iv:plkV/JigMwyRsq2tpn4YH8rapLx1DEZGUeS/XeR1DM8=,tag:VxDpoWcHcomjOHBjaKwybQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15vnvhx4cx7pf086re4gcm6hdg5gc4cpw4942n943xw93gep32d2sx35yxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdkZmR0t2b2hjTVQ5SnBR
            U2V1MzN6ZktyaGFmYUQ3MlMweXhqRVBzZVhrCmNpZVV5S3lldTRIbG45WnlEM0tQ
            UW1iSlRWTjI2YXVJOFFCdG1GbmNpSE0KLS0tIHBvZWRtbGVPdmRQMnM2UWIwam5j
            WmsvcVJzaUtwbk5RcGh2OUUxTmpvUXcKRY9ojzKaUZbin8YyAGvP3UjnjRA8QINW
            ENIU83JrpggvkhcH4IDJkD4GzOVu0FJ1oYQvk6dWejdlcRvpJfqMSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T12:23:21Z"
    mac: ENC[AES256_GCM,data:iLvIfqoapTW3uxuYBToB80iaFgmKr05fkFw5d0Tgj2t5cT7KSrvQYsWBwKW+XDlPGcS/4vnigR7Hbk85W4od2dasYjF5urkVkPHvd+Lnpj8zFyTM5x4r2J/wEYZn6zZLPN8gY3CI16lL7hN6S2Zm7nCvpPUgN9ZvzrUc79WuE3Y=,iv:FSwm4lffXFKhB1Ny8k3+wf3SXwZmlQX7uMV/WRts2gc=,tag:u1Ct2EQ74Cw5CIsHr+SZeg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
