database:
    password: ENC[AES256_GCM,data:HrLc/QXrDm7gKcBc,iv:G8GY55d7iGeszWIUDlfbuIASFk7TSxz8OszlOYYPuWs=,tag:DOmX/GavDoyEe/WiDsVKQw==,type:str]
secrets:
    auth_token: ENC[AES256_GCM,data:PbGKSWulnA==,iv:4oZTN9ycFRHlSBekT2+r18TJEOdJp6Rp86Jkao/bRko=,tag:8os8TBw5yuGUwokHc3tIzw==,type:str]
    api_secret: ENC[AES256_GCM,data:PXX/kDpFlw==,iv:s0yH+JS3+8a6OwPPZxSFbdTnetpVV6u+q4y68tZ1mKg=,tag:47plOHrBWwIDOAfvn/95XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15vnvhx4cx7pf086re4gcm6hdg5gc4cpw4942n943xw93gep32d2sx35yxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV1ZpK0oxcDd5YUo0anhN
            SDE3N0JuR0xUbWFScTdIeHp4SWJMZlB4VVQ0CnRKbXNwMWFWc2cxN3VwdGkxZEd5
            YVJMSm8vQkZxVzZEVCs3dVMwUUlLVVkKLS0tIDNXK2Y3Y2w1NjEzZkZVK3ZWZVhX
            bmpuY3J6TEpTbHRCR29ranlrMWthWXcKXkk2S2W4ISOzEEZEOwYzCEUE54TG9D5h
            ax3KPTMISOz6zEWTvDidXGiAIqXTfXw4eyzUIljgM9ij4/ogQSxiiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T12:20:56Z"
    mac: ENC[AES256_GCM,data:a02Fyd874AHiSwqRpa79+L8bFLPsev5wGOBzplWxe7vAJuDFZ8PT6pqUi+u4Qa0CNcBfD1wY1xgqhK6rCYLVp/RndWL6iQSV1ItfppJTI42G5blO9z9phAeNuPjCQ4UXd9uThif7An9MUtCw4d3vRaIT5ygkFMDb5J1BeROZgKo=,iv:GTlTUYJV6cjfSfQvXxJueWmLdLLprUDm/U77YVEhouQ=,tag:Jse6jw7QIPW/PojtWJYfdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
