database:
    password: ENC[AES256_GCM,data:nEh0p485sC5S8qI3Jg==,iv:DNIOwVk+YPdMpJ/JzPuAVBF/8pxMsg15QhfW4UEYjAs=,tag:S2xQ4FDZyCNrL6DfGMyOjA==,type:str]
secrets:
    auth_token: ENC[AES256_GCM,data:DxILmFUXneA=,iv:Opq6bOBzfxczSLsEo3tSMhZNFJTatb2vj0RBmSv1000=,tag:OdrzKhEjxaMruat93YGUNg==,type:str]
    api_secret: ENC[AES256_GCM,data:5HS46zY9biY=,iv:rc/UlHpMiVmONq0BzFb4rwaEQqaAbgr+MXnMplF9rhQ=,tag:EfKO2bpWTTPS5wwgm+20ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fcm7m3zekz38agqr2wyv62n5xuwhnyu4yq9unj3lftwervtq2d6qgc7auk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVWMvemNCK2hrSmp4dCtE
            Qjh4dkRyYUIxOGtXZVVENk5hR3BpbDQxWXg0CitPaVN1VThDNTdVTHVDeGh4bFVx
            NzRMSmdvSEd4Y0FTNFlrVDYvcVM5SDQKLS0tIEFodHBMQjFyOFAvcXNkN2piV1ZY
            dlVaQldKUnlXZmlYUjlCWGtoWUFFVTAKsABYIDik+TUAl5b4VturRGlaQ7hYVTQK
            D9mOJ9NDD3na6CnJQXuX5wAcWv3kdCx+hoZWjVf9KJ9+7jso8mMOvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-08T13:15:09Z"
    mac: ENC[AES256_GCM,data:sz/5ZMjnvHE886U8NrHFbvQNdY04mpGEdqapoIh+vaEpuMgiXn3LUDHMR0tpEPi+xI30WeDtGOCOpfik8KHA73z3DDZmEdEGBus5kIONBT7XnEKpdp7ozRF9SH85CFYs69ZZOpyrDHvPhvkJdQUrJA8u2nKraWM35CDtaIsNA7I=,iv:sPauivkXNq/5Ls4nkFeSUzVx6LMNlcMtZXB6zOa5JYA=,tag:YJWfXsmUa8E/YC05BI1zkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
